<div class="logo">
    <a href="http://www.creative-tim.com" class="simple-text">
        Creative Tim
    </a>
</div>

<ul class="nav">
    <li class="active">
        <a href="<?= APP_URI_ADMIN ?>/abertura">
            <i class="pe-7s-graph"></i>
            <p>Dashboard</p>
        </a>
    </li>
    <!--li>
        <a href="< ?= APP_URI_ADMIN ? >/usuarios">
            <i class="pe-7s-note2"></i>
            <p>Lista de Usuarios</p>
        </a>
    </li-->
    <li>
        <a href="<?= APP_URI_ADMIN ?>/usuario/novo">
            <i class="pe-7s-note2"></i>
            <p>Cadastro de Usuários</p>
        </a>
    </li>

    <li>
        <a href="<?= APP_URI_ADMIN ?>/respostas/lista">
            <i class="pe-7s-user"></i>
            <p>Tabela de respostas</p> 
        </a>
    </li>
    <li>
        <a href="<?= APP_URI_ADMIN ?>/sair">
            <i class="pe-7s-bell"></i>
            <p>Sair</p>
        </a>
    </li>
</ul>