<?php include(APP_URI_TEMPLATES_ADMIN.'/_header.phtml'); ?>



<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <?php include(APP_URI_TEMPLATES_ADMIN.'/_menu.phtml'); ?>
    	</div>
    </div>

    <div class="main-panel">
        
    	<?php include(APP_URI_TEMPLATES_ADMIN.'/_topbar.phtml'); ?>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card ">
                            <div class="header">
                                <h4 class="title">Lista de usuarios</h4>

                            </div>
                            <div class="content">
                                <div class="content table-responsive table-full-width">
                                    <table class="table table-hover table-striped">
	                                    <thead>
	                                        <th>ID</th>
	                                        <th>Nome</th>
	                                        <th>Login</th>
	                                        <th>Ação</th>
	                                    </thead>
	                                    <tbody>
	                                        <?php 
	                                        foreach($lista as $key => $conteudo){ 
	                                        	?>
	                                            <tr>
	                                                <td><?= $conteudo['usuario_id'] ?></td>
	                                                <td><?= $conteudo['usuario_nome'] ?></td>
	                                                <td><?= $conteudo['usuario_login'] ?></td>
	                                                <td>
	                                                	<a href="<?= APP_URI_ADMIN ?>/usuario/editar/<?= $conteudo['usuario_id'] ?>">Editar</a> 
	                                                	| 
	                                                	<a href="<?= APP_URI_ADMIN ?>/usuario/delete/<?= $conteudo['usuario_id'] ?>">Delete</a>
	                                                </td>
	                                            </tr>
	                                        	<?php 
	                                        }
	                                        ?>
	                                    </tbody>
	                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>


        <?php include(APP_URI_TEMPLATES_ADMIN.'/_footer.phtml'); ?>

    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
	<script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/bootstrap-checkbox-radio-switch.js"></script>

	<!--  Charts Plugin -->
	<script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/light-bootstrap-dashboard.js"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/demo.js"></script>

</html>


