<?php include(APP_URI_TEMPLATES_ADMIN.'/_header.phtml'); ?>



<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

        <div class="sidebar-wrapper">
            <?php include(APP_URI_TEMPLATES_ADMIN.'/_menu.phtml'); ?>
        </div>
    </div>

    <div class="main-panel">
        
        <?php include(APP_URI_TEMPLATES_ADMIN.'/_topbar.phtml'); ?>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">

                            <div class="header">
                                <h4 class="title">Lista de Usuarios</h4>
                            </div>
                            <div class="content">
                    
                                <form name="form-login" id="form-login" method="post" action="<?= APP_URI ?>/admin/usuario/<?= $flag ?>">
                                    <input type="hidden" name="usuario_id" id="usuario_id" class="form-control" value="<?= @$dados['usuario_id'] ?>">
                                    <div class="form-group">
                                        Nome: <input type="text" name="usuario_nome" id="usuario_nome" class="form-control" value="<?= @$dados['usuario_nome'] ?>">
                                    </div>
                                    <div class="form-group">
                                        Login: <input type="text" name="usuario_login" id="usuario_login" class="form-control" value="<?= @$dados['usuario_login'] ?>">
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" name="entrar" id="entrar" class="form-control" value="Salvar">
                                    </div>
                                </form>


                            </div>
                            
                        </div>
                    </div>

                </div>

                <?php if(@$dados['usuario_id']){ ?>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">

                                <div class="header">
                                    <h4 class="title">Nova Senha</h4>
                                </div>
                                <div class="content">
                        
                                    <form name="form-login" id="form-login" method="post" action="<?= APP_URI ?>/admin/usuario/editasenha">
                                        <input type="hidden" name="usuario_id" id="usuario_id" class="form-control" value="<?= @$dados['usuario_id'] ?>">
                                        <div class="form-group">
                                            Senha: <input type="password" name="usuario_senha" id="usuario_senha" class="form-control" value="">
                                        </div>

                                        <div class="form-group">
                                            <input type="submit" name="entrar" id="entrar" class="form-control" value="Salvar">
                                        </div>
                                    </form>


                                </div>
                                
                            </div>
                        </div>

                    </div>
                <?php } ?>

            </div>

           
        </div>


        <?php include(APP_URI_TEMPLATES_ADMIN.'/_footer.phtml'); ?>

    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  Checkbox, Radio & Switch Plugins -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/bootstrap-checkbox-radio-switch.js"></script>

    <!--  Charts Plugin -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/light-bootstrap-dashboard.js"></script>

    <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
    <script src="<?= APP_URI_TEMPLATES ?>/admin/light-bootstrap-dashboard-master/assets/js/demo.js"></script>

</html>


