<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="<?= APP_URI_TEMPLATES ?>/css/style.css">
    </head>
    <body>
        <div class="container">

            <h1>Busca</h1>

            <div>
                <form name="form-busca" method="post" action="#">
                    <input type="text" name="cep" value="">
                    <input type="submit" name="buscar" value="Buscar">
                </form>
            </div>

            <div>
                <?php
                foreach($lista_pratos as $key_prato => $value_prato){
                    echo "Nome: ".$value_prato['nome'];
                    echo "<br />";
                    echo "Preco: ".$value_prato['preco'];
                    echo "<br />";
                    echo "Descrição: ".$value_prato['descricao'];
                    echo "<br />";echo "<br />";
                }
                ?>
            </div>

        </div>

    </body>
</html>
