<!DOCTYPE html>
<html>
    <head>
        <titlePesquisa Exposição a Radiação Ionizante</title>

        <meta name="viewport" content="initial-scale=1.0">
        <meta charset="utf-8">
        
        <link rel="stylesheet" href="<?= APP_URI_TEMPLATES ?>/css/style.css">

        <link rel="stylesheet" href="<?= APP_URI_TEMPLATES ?>/css/bootstrap.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>


        <style>
            body {font-family: 'Montserrat', sans-serif; font-size: 14px;}
            input[type="text"] {width: 85%; padding: 1%;}
            select {padding: 1%;}
            textarea {width: 85%; height: 85px;}

            #conteudo {width: 80%; margin: 0 auto;}

            .titulo-grande {background-color: #673ab7; color: #ffffff; font-size: 1.5em; padding: 1%; text-align: center; margin-bottom: 1%}

            .div-linhas {padding-bottom: 2%;}
            .label-campos {background-color: #efedf2; padding: 1%; margin-bottom: 1%;}

            #obrigado {font-size: 3em; text-align: center; margin-top: 5%;}
        </style>

    </head>
    <body>
        
        <div id="conteudo">

            <div id="obrigado">Agradecemos sua participação!</div>

        </div>

    </body>
</html>
