<?php include(APP_URI_TEMPLATES_ADMIN.'/_header.phtml'); ?>

        <div class="container">

            <h1>Cadastro</h1>

            <?php include(APP_URI_TEMPLATES_ADMIN.'/_menu.phtml'); ?>

            <div class="col-md-12">
                <div class="col-md-6">
                    <form name="form-login" id="form-login" method="post" action="<?= APP_URI ?>admin/cadastro/cadastro">
                        <div class="form-group">
                            Nome: <input type="text" name="corrida_nome" id="corrida_nome" class="form-control" value="">
                        </div>
                        <div class="form-group">
                            Data <input type="date" name="corrida_data" id="corrida_data" class="form-control" value="">
                        </div>
                        <div class="form-group">
                            Preço <input type="number" min="1" step="any" name="corrida_preco" id="corrida_preco" class="form-control" value="">
                        </div>
                        <div class="form-group">
                            Endereço <input type="text" name="corrida_endereco" id="corrida_endereco" class="form-control" value="">
                        </div>
                        <div class="form-group">
                            Cidade <input type="text" name="corrida_cidade" id="corrida_cidade" class="form-control" value="">
                        </div>
                        <div class="form-group">
                            Estado <input type="text" name="corrida_uf" id="corrida_uf" class="form-control" value="">
                        </div>

                        <div class="form-group">
                            <input type="submit" name="entrar" id="entrar" class="form-control" value="Entrar">
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-12">
                <div class="col-md-6">
                <?php 
                if(@$msg){
                    ?>
                    <div class="alert alert-success">
                        <?php print_r($msg);  ?>
                    </div>
                    <?php
                }
                ?>
                </div>
            </div>

        </div>

<?php include(APP_URI_TEMPLATES_ADMIN.'/_footer.phtml'); ?>
